### PR TITLE
Implemented full name detection

### PR DESCRIPTION
**Pull request by mjonesncat**

### CODE REVIEW

**Review by Kgeddis — DISMISSED** [review]
Looks Good

**Review by trbynum — APPROVED** [review]
Everything looks good! Excellent work

**Review by Kgeddis — APPROVED** [review]
looks good

**Review by trbynum — DISMISSED** [review]
Good to go.

**Review by Kgeddis — CHANGES_REQUESTED** [review]
fix indentation

**Review by Kgeddis — APPROVED** [review]

**Review by trbynum — APPROVED** [review]
Looks good!

**Pull request merged**
