### PR TITLE
Implemented Marital Status Detection

### PR DESCRIPTION
**Pull request by jenniferibe**

### CODE REVIEW

**Comment by NicholasDewberryOfficial** [comment]
Hmm, I'll look into it

**Comment by NicholasDewberryOfficial** [comment]
I checked the code, and it looks like you added your test, then deleted it? Not sure..

How are you planning on detecting marital status? If you want to use regex, you have to modify pii_scan.py like how [Caleb did it](https://github.com/NCATComp410/comp410_fall_2023/pull/68/files)

What you're doing now will error out - as you're calling a presidio recognizer that doesn't exist.

**Comment by NicholasDewberryOfficial** [comment]
Hello, found the error you brought up on groupme. You just had to change the assertIn statements to use MARITALSTATS rather than the other thingy you had.

Get some pl to check over for u

**Comment by NicholasDewberryOfficial** [comment]
I see a merge error. Hopefully I can solve it real quick.

**Review by NicholasDewberryOfficial — APPROVED** [review]
this merge conflict business is cray. HOPEFULLY now it works.

**Review by NicholasDewberryOfficial — APPROVED** [review]

**Review by NicholasDewberryOfficial — DISMISSED** [review]

**Review by ThatGuy65 — DISMISSED** [review]
Seems like issues have been mostly sorted out, however make sure that the assignees and reviewers are correct

**Review by mthorn12 — DISMISSED** [review]
Great implementation!

**Review by claesmk — APPROVED** [review]
Merged resolved conflicts for you - looks good now

**Pull request merged**
