### PR TITLE
Adding test cases for detecting eye color.

### PR DESCRIPTION
**Pull request by Lesterconey**
I did not know how to add my PII to the existing list so I could not make the correct assertions.

### CODE REVIEW

**Review by claesmk — CHANGES_REQUESTED** [review]
As I pointed out in your issue [comments](https://github.com/NCATComp410/comp410_fall_2023/issues/30#issuecomment-1727544579) you need to implement a custom recognizer to make this work correctly. Right now you aren't detecting anything.   A good place to add your custom recognizer would be right after the [uuid_recognizer](https://github.com/NCATComp410/comp410_fall_2023/blob/dd0d4ed8c9f1bf930c96793e85ec0beb003e4c8d/pii_scan.py#L55C12-L55C12) in analyze_text

**Review by tfortobi — DISMISSED** [review]
Good job

**Review by chelseavuata — APPROVED** [review]
Outstanding job!!!!

**Review by tfortobi — APPROVED** [review]
good

**Review by claesmk — APPROVED** [review]
Looks OK

**Pull request merged**
