### PR TITLE
32 detect interests

### PR DESCRIPTION
**Pull request by Caleb-Andrew-Mitchell**
My three test cases are now updated.

### CODE REVIEW

**Review by claesmk — APPROVED** [review]

**Comment by NicholasDewberryOfficial** [comment]
Very cool. Nice regex. Have you tested this with longer sentences, such as "I like bibleman, but I do not like chris-chan"? or something like "  

I'm curious as to what it would return. 

Something to keep in mind is that this could turn messy very quickly once we start reading from large pieces of text. Nice work though!

**Review by NicholasDewberryOfficial — COMMENTED** [review]
Approval comment

**Review by NicholasDewberryOfficial — DISMISSED** [review]

**Comment by Caleb-Andrew-Mitchell** [comment]
> Very cool. Nice regex. Have you tested this with longer sentences, such as "I like Bibleman, but I do not like chris-chan"? or something like "
> 
> I'm curious as to what it would return.
> 
> Something to keep in mind is that this could turn messy very quickly once we start reading from large pieces of text. Nice work though!

Hey, Nick. I'm glad you asked this. Right now, the regex checks to see if any words or phrases follow certain words such as "like, love, enjoy, or interested in" but phrases such as "don't like" or "do not like" are rejected. Since the sentence you decribed has the phrase "I like Bibleman," then the test would pass.

**Review by NicholasDewberryOfficial — APPROVED** [review]
Re-reviewing. Everything looks alright - thanks for including my new testcase.


Does your test_interests include 2 test cases and 1 negative case? I forgot to check for that earlier ( I think it does)

**Review by ThatGuy65 — APPROVED** [review]
This seems solid. Good work.

**Pull request merged**
