### PR TITLE
#7 Identify American Address (pull request)

### PR DESCRIPTION
**Pull request by NicholasDewberryOfficial**
Hello. I modified pii_scan to include my custom regex 

and I also modified teamhaciketcts.py as well. 

Nothing too complex.

### CODE REVIEW

**Comment by claesmk** [comment]
@NicholasDewberryOfficial Did you use vscode inside a codespace to develop this?  There were some indentation errors that I would not expect to see from vscode.  The top of your file also got replicated somehow.  I fixed these two things and pushed it.

**Review by claesmk — DISMISSED** [review]
Looks good.  Love that you put in the extra effort to implement the custom recognizer.

**Comment by claesmk** [comment]
@NicholasDewberryOfficial make sure you add someone else on your team as a reviewer.  Once they have reviewed and approved you will be able to merge this PR

**Comment by Caleb-Andrew-Mitchell** [comment]
Your regex looks very nice, I'm impressed.

**Review by Caleb-Andrew-Mitchell — APPROVED** [review]
I like how you made your regex. It's very detailed.

**Comment by NicholasDewberryOfficial** [comment]
NOTE: theres a merge conflict. Ill solve it by 2pm hopefully today.

**Review by ThatGuy65 — APPROVED** [review]
Custom Regex is well thought out and functional. 
Nice clean code all around!

**Comment by NicholasDewberryOfficial** [comment]
OK.  branch has conflicts that must be resolved. Im on it.

**Comment by NicholasDewberryOfficial** [comment]
Now I need to rebuild.

**Comment by NicholasDewberryOfficial** [comment]
ok now im lost. I solved a merge conflict - yet somehow i cant see if it would cause a problem

**Review by ThatGuy65 — APPROVED** [review]
Re Approving for merge conflict fixes

**Review by Caleb-Andrew-Mitchell — APPROVED** [review]
Re-approving the new code.

**Pull request merged**
