### PR TITLE
Implemented credit score detection

### PR DESCRIPTION
**Pull request by rdouglas202**

### CODE REVIEW

**Review by claesmk — DISMISSED** [review]
Nice work validating credit scores with regex. Can you link the reference you used to determine valid credit scores?

You have some merge conflicts you need to resolve before you can merge.  Keep in mind the additional [video](https://youtu.be/lv9yD87s3sQ) listed in the sprint instructions I made should help with that. 

Please make sure someone else on your team reviews as well

I'll approve what you have done, it works ok you don't have to improve on it, however, here are a few thoughts:

(1) You could use the [context words](https://microsoft.github.io/presidio/tutorial/06_context/) approach to use context as modifiers to your detection scores. A 3 digit number is easily confused with a street address, etc.  Context would help avoid that.

(2) You have not tested all the alternatives in your regex.  In real projects regex is often responsible for some pretty bad bugs.  Some addition test cases would include numbers in the 3xx range (I'm actually not sure why you made 3xx a special range vs just doing [3-7]) You should also specifically test 850

**Comment by rdouglas202** [comment]
@claesmk I referenced this link stating the range of a credit score 
[https://www.experian.com/blogs/ask-experian/credit-education/score-basics/what-is-a-good-credit-score/](url)

1) This is a good point to have the detector recognize to word "credit score" instead of a 3-digit  number within a range that could also be classified as an address.

2) Yes some edge cases could be added to the unit tests implemented here.

**Comment by jewelworks** [comment]
Looks good Ryan!

**Review by jewelworks — APPROVED** [review]
Looks good Ryan!

**Review by tfortobi — APPROVED** [review]
Good work

**Pull request merged**
