### PR TITLE
Added instructions for image detection capability

### PR DESCRIPTION
**Pull request by ThatGuy65**
Added to test_team_hackitects.py is the test bench and import requirements in order to operate image detection, as mentioned in #79 . Due to the chaos of inserting images and dependencies into requirements.txt (that was resolved in #92  ), the changes added were added to Sprint 3 were in a form of a comment, in order to prevent any conflicts. The code added, when assisted with the correct dependencies and image files, works as proven in #79 , and is inherently resistant to false positives due to the nature of the package leveraged. This is because if a face is not detected in an image, the array that holds faces will not be updated and thus a false positive will not occur. In addition, the package for identifying images is meant to handle false positives with the "tolerance" parameter. that can be adjusted, but the default value of 0.6 is very good at detecting faces as is. 

More here: 
https://pypi.org/project/face-recognition/

### CODE REVIEW

**Comment by ThatGuy65** [comment]
In addition to what was detailed in my pull request, the test cases provided had none for images, which is my PII. in order to rectify this, I had my own test cases tested, and the reason my commits were in comments were to not break everything all over again.

**Review by mthorn12 — DISMISSED** [review]
I looked at what you said & this looks good. You probably will have to work with Mr.Claes to ensure your code will work probably and all those issues are resolved.

**Comment by claesmk** [comment]
@ThatGuy65 As previously commented I was planning to help you out with this for sprint-4.  You don't need to worry about grades for sprint-3.  You've done fantastic work so far so you'll get full credit for this.

The approach I was planning to use is to create a completely new file for your unit tests - such as test_face_recognize.py - there is something called the "skip decorator" as part of the python [unittest](https://docs.python.org/3/library/unittest.html) infrastructure.  What you'll want to do is check to see if your libraries have been installed.  If not, skip your tests, if they have, then you'd run them.

**Comment by claesmk** [comment]
@ThatGuy65 I restructured your commit to allow face recognition to execute conditionally depending on if it is installed or not.  Please take a look at the changes I made

There are probably a couple of different ways to handle this problem:

1. Enable caching of pip packages which *should* allow face_recognize to cache and install much more quickly.  The downside here is that GitHub caches have a rapid expiry (7 days) which makes this not practical for this project.  If this was a very active project it would probably work well. 
2. Create a custom docker image for this project. I think this would probably work well.  Anyone creating a new codespace would automatically load the image which would have all the dependencies prebuilt into it.  The only downside is the maintenance involved with updating the image when necessary.
3. Only execute face recognition tests when it is actually installed and warn otherwise.  This is the solution I decided to go with since it avoids the aforementioned problems.  The downside is that face_recognition is not protected by routine unit testing.

**Review by claesmk — APPROVED** [review]

**Review by NicholasDewberryOfficial — APPROVED** [review]
Hello, sorry for the late review. I thought I already did this. Nice work!

**Pull request merged**
